name: dogs_case
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  
  dio: ^5.4.1
  json_serializable: ^6.7.1
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  auto_route: ^7.8.4
  # freezed: ^2.4.7
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  path_provider_foundation: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/settings/
